Solace plugin
Axway-API-Builder-Ext/api-builder-extras pull request #23
Opened 2020-05-27 17:26 UTC by pltod2

2020-05-28 07:00 UTC, cwiechmann commented
Hi @pltod2, is this supposed to become a real plugin?
I understood in the demo you gave this is some kind of PoC.
If yes, we should add some documentation about the use-case, what Solace is, how to use it, etc.

At the moment it is very bare. Just let me know.

Chris

2020-05-28 09:02 UTC, pltod2 commented
Hi @cwiechmann, I believe the expectations are this will become a real plugin. But you are right this is WIP. It works for the publish and subscribe cases I was demonstrating but yes don't merge it yet. Probably, I should have flagged it differently or shouldn't submitted the PR at all at this stage. Anyway, for the moment I renamed the PR as WIP, will add test suite and will polish it and then will come back to you for review.

2020-05-28 09:20 UTC, cwiechmann commented
I flagged this PR as a draft.

2021-08-23 08:28 UTC, cwiechmann commented
What about this PR @pltod2, should we close this or what is the status?

2021-09-07 13:34 UTC, cwiechmann commented on api-builder-plugin-solace/README.md
> +After creating your API Builder service (`api-builder init`), you can install this plugin using npm:
gdfsfgsdf

2021-09-07 13:34 UTC, cwiechmann requested changes
Test

2021-09-07 13:34 UTC, cwiechmann commented on api-builder-plugin-solace/README.md
> +
Test line 1

2021-09-07 13:34 UTC, cwiechmann commented on api-builder-plugin-solace/config/solace.default.js
> +			vpnName:  process.env.SOLACE_VPN,
Test

2021-09-07 15:33 UTC, pltod2 commented
@cwiechmann sorry, did not see your previous comment. Yes, we can close and I am closing this since we have released this as official plugin.

2021-09-07 15:33 UTC, closed without merging